# -*- coding: utf-8 -*-
"""Classification models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15iVIc5451wPTFmpJ1DcK58e8t0ZKWCfv
"""

!pip install gensim

"""# Step 1 — Import libraries"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.sparse import hstack

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

from gensim.models import Word2Vec

"""# Step 2 — Load data"""

# Load dataset
df = pd.read_csv("books_with_clusters.csv")

# Keep only rows with valid text and labels
df = df.dropna(subset=["text_clean", "keyword_category"]).copy()

# Convert to string just in case
df["text_clean"] = df["text_clean"].astype(str)
df["keyword_category"] = df["keyword_category"].astype(str)

print("Dataset shape:", df.shape)
print(df[["Title", "text_clean", "keyword_category"]].head())
print("\nCategory distribution:")
print(df["keyword_category"].value_counts())

"""# Step 3 — Train/test split"""

X_text = df["text_clean"]
y = df["keyword_category"]

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train size:", len(X_train_text))
print("Test size:", len(X_test_text))

"""# Step 4 — Build BoW features"""

bow_vectorizer = CountVectorizer(
    max_features=5000,
    min_df=2,
    max_df=0.95,
    ngram_range=(1, 2)
)

X_train_bow = bow_vectorizer.fit_transform(X_train_text)
X_test_bow = bow_vectorizer.transform(X_test_text)

print("BoW train shape:", X_train_bow.shape)
print("BoW test shape:", X_test_bow.shape)

"""# Step 5 — Build TF-IDF features"""

tfidf_vectorizer = TfidfVectorizer(
    max_features=5000,
    min_df=2,
    max_df=0.95,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_text)
X_test_tfidf = tfidf_vectorizer.transform(X_test_text)

print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF test shape:", X_test_tfidf.shape)

"""# Step 6 — Build LDA features"""

n_topics = 10

lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    learning_method="batch"
)

X_train_lda = lda_model.fit_transform(X_train_bow)
X_test_lda = lda_model.transform(X_test_bow)

print("LDA train shape:", X_train_lda.shape)
print("LDA test shape:", X_test_lda.shape)

"""# Step 7 — Build Word Embedding features"""

# Tokenize text
train_tokens = [text.split() for text in X_train_text]
test_tokens = [text.split() for text in X_test_text]

# Train Word2Vec on training corpus only
w2v_model = Word2Vec(
    sentences=train_tokens,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    seed=42
)

embedding_dim = w2v_model.vector_size

def document_vector(tokens, model, dim):
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    if len(vectors) == 0:
        return np.zeros(dim)
    return np.mean(vectors, axis=0)

X_train_embed = np.array([document_vector(tokens, w2v_model, embedding_dim) for tokens in train_tokens])
X_test_embed = np.array([document_vector(tokens, w2v_model, embedding_dim) for tokens in test_tokens])

print("Word Embedding train shape:", X_train_embed.shape)
print("Word Embedding test shape:", X_test_embed.shape)

"""# Step 8 — Store all feature sets"""

feature_sets = {
    "BoW": (X_train_bow, X_test_bow),
    "TF-IDF": (X_train_tfidf, X_test_tfidf),
    "LDA": (X_train_lda, X_test_lda),
    "WordEmbedding": (X_train_embed, X_test_embed)
}

for name, (Xtr, Xte) in feature_sets.items():
    print(name, "->", Xtr.shape, Xte.shape)

"""# Step 9 — Define models"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1),
    "SVM": LinearSVC(random_state=42)
}

"""# Step 10 — Run models"""

results = []
all_predictions = {}

for feature_name, (Xtr, Xte) in feature_sets.items():
    print(f"\n========== Feature: {feature_name} ==========")

    for model_name, model in models.items():
        print(f"Training {model_name} on {feature_name}...")

        model.fit(Xtr, y_train)
        y_pred = model.predict(Xte)

        acc = accuracy_score(y_test, y_pred)
        precision, recall, f1, _ = precision_recall_fscore_support(
            y_test, y_pred, average="weighted", zero_division=0
        )

        results.append({
            "Feature": feature_name,
            "Model": model_name,
            "Accuracy": acc,
            "Precision": precision,
            "Recall": recall,
            "F1-score": f1
        })

        all_predictions[(feature_name, model_name)] = {
            "model": model,
            "y_pred": y_pred
        }

        print(f"Accuracy: {acc:.4f}, F1-score: {f1:.4f}")

"""# Step 11 - Summary table"""

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by=["F1-score", "Accuracy"], ascending=False).reset_index(drop=True)

results_df.style.format({
    "Accuracy": "{:.4f}",
    "Precision": "{:.4f}",
    "Recall": "{:.4f}",
    "F1-score": "{:.4f}"
})

"""# Step 12 — Compare results visually"""

plt.figure(figsize=(12, 6))

for model_name in results_df["Model"].unique():
    subset = results_df[results_df["Model"] == model_name]
    plt.plot(subset["Feature"], subset["F1-score"], marker="o", label=model_name)

plt.title("F1-score Comparison Across Features and Models")
plt.xlabel("Feature Representation")
plt.ylabel("Weighted F1-score")
plt.legend()
plt.xticks(rotation=15)
plt.show()

"""# Step 13 — Find the best two model-feature combinations"""

best_row = results_df.iloc[0]
best_feature = best_row["Feature"]
best_model_name = best_row["Model"]

print("Feature:", best_feature)
print("Model:", best_model_name)
print(best_row)

second_best_row = results_df.iloc[1]
second_best_feature = second_best_row["Feature"]
second_best_model_name = second_best_row["Model"]

print("Feature:", second_best_feature)
print("Model:", second_best_model_name)
print(second_best_row)

"""# Step 14 — Classification report for the best two combinations"""

best_pred = all_predictions[(best_feature, best_model_name)]["y_pred"]

print(f"Best combination: {best_model_name} + {best_feature}\n")
print(classification_report(y_test, best_pred, zero_division=0))

second_best_pred = all_predictions[(second_best_feature, second_best_model_name)]["y_pred"]

print(f"Combination: {second_best_model_name} + {second_best_feature}\n")
print(classification_report(y_test, second_best_pred, zero_division=0))

"""# Step 15 — Confusion matrix for the best two combinations"""

labels = sorted(y.unique())

cm = confusion_matrix(y_test, best_pred, labels=labels)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)

fig, ax = plt.subplots(figsize=(10, 8))
disp.plot(ax=ax, xticks_rotation=45, cmap="Blues", colorbar=False)
plt.title(f"Confusion Matrix: {best_model_name} + {best_feature}")
plt.show()

labels = sorted(y.unique())

cm = confusion_matrix(y_test, second_best_pred, labels=labels)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)

fig, ax = plt.subplots(figsize=(10, 8))
disp.plot(ax=ax, xticks_rotation=45, cmap="Blues", colorbar=False)
plt.title(f"Confusion Matrix: {second_best_model_name} + {second_best_feature}")
plt.show()

"""# Step 16 — error analysis for the best two combination"""

def get_top_misclassified_full(feature, model_name, df_test, top_n=5):

    y_pred = all_predictions[(feature, model_name)]["y_pred"]

    temp_df = df_test.copy()
    temp_df["true_label"] = y_test.values
    temp_df["predicted_label"] = y_pred

    errors_df = temp_df[
        temp_df["true_label"] != temp_df["predicted_label"]
    ].copy()

    errors_df["text_length"] = errors_df["text_clean"].apply(len)
    errors_df = errors_df.sort_values(by="text_length", ascending=False)

    return errors_df.head(top_n)

df_test_full = df.loc[X_test_text.index].copy()

top1_errors = get_top_misclassified_full(best_row["Feature"], best_row["Model"], df_test_full)
top2_errors = get_top_misclassified_full(second_best_row["Feature"], second_best_row["Model"], df_test_full)

print("Top 5 misclassified samples for Random Forest+BoW:")
print(top1_errors[["Title", "true_label", "predicted_label", "Description"]])
print("\nTop 5 misclassified samples for Random Forest+TF-IDF:")
print(top2_errors[["Title", "true_label", "predicted_label", "Description"]])

"""# Cosine Similarity Recommender

# Step 1 — Load data and TF-IDF matrix
"""

import pandas as pd
import numpy as np
from scipy.sparse import load_npz

# Load the processed book dataset
df = pd.read_csv("books_with_clusters.csv")

# Load the TF-IDF matrix created earlier
X = load_npz("tfidf_matrix.npz")

print("Dataset shape:", df.shape)
print("TF-IDF matrix shape:", X.shape)
print(df[["Title", "keyword_category"]].head())

"""# Step 2 — Compute cosine similarity matrix"""

from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity between all books
cosine_sim = cosine_similarity(X, X)

print("Cosine similarity matrix shape:", cosine_sim.shape)

"""# Step 3 — Create a title-to-index mapping"""

# Create a mapping from book title to row index
indices = pd.Series(df.index, index=df["Title"]).drop_duplicates()

print("Number of unique titles:", len(indices))

"""# Step 4 — Build the recommendation function"""

def recommend_books(title, top_n=10):
    """
    Recommend top_n books similar to the given title
    based on cosine similarity of TF-IDF features.
    """

    # Check whether the title exists
    if title not in indices:
        return f"Book '{title}' not found in the dataset."

    # Get the index of the selected book
    idx = indices[title]

    # Get pairwise similarity scores for that book
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort books by similarity score in descending order
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Exclude the book itself and keep top_n similar books
    sim_scores = sim_scores[1:top_n+1]

    # Get indices of recommended books
    book_indices = [i[0] for i in sim_scores]
    similarity_scores = [i[1] for i in sim_scores]

    # Build result dataframe
    recommendations = df.iloc[book_indices][["Title", "Authors", "keyword_category", "Description"]].copy()
    recommendations["similarity_score"] = similarity_scores

    return recommendations

"""# Step 5 — Test the recommender"""

print(df["Title"].head(20).tolist())

"""# Step 6 — Show one sample recommendation nicely"""

sample_title = df["Title"].iloc[0]
print("Selected book:", sample_title)

recommend_books(sample_title, top_n=10)

"""# Step 7 — Add a simple visualization"""

import matplotlib.pyplot as plt

sample_title = df["Title"].iloc[0]
result = recommend_books(sample_title, top_n=10)

plt.figure(figsize=(10, 5))
plt.bar(result["Title"], result["similarity_score"])
plt.xticks(rotation=75)
plt.title(f"Top 10 Recommendations for '{sample_title}'")
plt.xlabel("Recommended Books")
plt.ylabel("Cosine Similarity Score")
plt.tight_layout()
plt.show()